### ISSUE TITLE
Add barplot that prints positive transactions above y-axis and negative transactions below y-axis

### ISSUE THREAD

**Issue by deSagaz** [jameshtwose/finance-dashboard#10]
Allows comparison of in/out flows.

Example: 

![image](https://user-images.githubusercontent.com/4922048/203963628-d2015005-f409-47c3-8675-b1148bb4c37c.png)

**Comment by jameshtwose** [comment]
I have now implemented this :-) 

![Screenshot 2022-12-13 at 14 17 35](https://user-images.githubusercontent.com/39407392/207328225-855a0a0a-876e-4a1a-8f68-0940d51f8423.png)

**Comment by jameshtwose** [comment]
@deSagaz you like? :-o
