### ISSUE TITLE
Do a preliminary check on the file uploaded

### ISSUE THREAD

**Issue by ltgio** [jameshtwose/finance-dashboard#5]
I tried to upload a pdf which includes not financial information and it would be good to provide an error message at least that the file is not in the right format. Right now the dashboard does not provide anything back.

**Comment by jameshtwose** [comment]
We have gone for this:
![Screenshot 2022-12-14 at 12 04 59](https://user-images.githubusercontent.com/39407392/207578933-6059a09c-9ba0-41f8-9d40-da10b9505328.png)
