### ISSUE TITLE
Better formatting of Date Column

### ISSUE THREAD

**Issue by ltgio** [jameshtwose/finance-dashboard#6]
In `Home/descriptives` the date column could be formatted better 

Right now it shows e.g., 2022-11-01T00:00:00
maybe you can convert the text like 1 November 2022 or 1 Nov 2022 as done in the ING app

**Comment by jameshtwose** [comment]
Done :-) 
![Screenshot 2022-12-14 at 12 24 25](https://user-images.githubusercontent.com/39407392/207582871-6f12fea4-fab6-4acc-879c-206616da7d01.png)
